//
// Created by Michael Davis on 30/03/2020.
//

#ifndef A_LESS_WRITEY_PAXOS_INSTANCEVALUESMANAGER_H
#define A_LESS_WRITEY_PAXOS_INSTANCEVALUESMANAGER_H
#endif //A_LESS_WRITEY_PAXOS_INSTANCEVALUESMANAGER_H
